# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Phill Farrugia
tagline:          'Blog'
description:      'Takes <a href="https://500px.com/phill_farrugia" target="_blank">photos</a>, writes <a href="http://twitter.com/phillfarrugia" target="_blank">words</a>, and <a href="https://github.com/phillfarrugia" target="_blank">codes</a> things.'
url:              http://phillfarrugia.com
baseurl:          /

author:
  name:           'Phill Farrugia'
  url:            https://twitter.com/phillfarrugia

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
